#!/bin/bash
#########################################################################################
#                                                                                       #
#                                                                                       #
#                 Setup firewalld for public web servers in the DMZ                     #
#                                                                                       #
#                                                                                       #
#########################################################################################

#########################################################################################
# Create New Services
#########################################################################################

# Tomcat (http) on port 8080

sudo firewall-cmd --permanent --new-service=tomcat-http
sudo firewall-cmd --permanent --service=tomcat-http --set-description="Tomcat server on port 8080"
sudo firewall-cmd --permanent --service=tomcat-http --set-short=tomcat-http
sudo firewall-cmd --permanent --service=tomcat-http --add-port=8080/tcp

# Secure Tomcat (https) on port 8443

sudo firewall-cmd --permanent --new-service=tomcat-http
sudo firewall-cmd --permanent --service=tomcat-http --set-description="Tomcat server on port 8443"
sudo firewall-cmd --permanent --service=tomcat-http --set-short=tomcat-https
sudo firewall-cmd --permanent --service=tomcat-http --add-port=8443/tcp

#########################################################################################


#########################################################################################
# Setup new zone
#########################################################################################

# Create new zone
sudo firewall-cmd --permanent --new-zone=publicweb

# Add services to zone

# Add services available to all IPs/Networks

# http(s)
sudo firewall-cmd --permanent --zone=publicweb --add-service=http
sudo firewall-cmd --permanent --zone=publicweb --add-service=https

# Tomcat
sudo firewall-cmd --permanent --zone=publicweb --add-service=tomcat-http
sudo firewall-cmd --permanent --zone=publicweb --add-service=tomcat-https

# Add Specific rich rules to allow the Management LAN to manage this instance

# Allow ssh from management LAN or firewall
sudo firewall-cmd --permanent --zone=publicweb --add-rich-rule 'rule family="ipv4" service name="ssh" source address="10.10.20.1" accept'
sudo firewall-cmd --permanent --zone=publicweb --add-rich-rule 'rule family="ipv4" service name="ssh" source address="10.10.10.0/24" accept'

# Allow Cockpit from management LAN
sudo firewall-cmd --permanent --zone=publicweb --add-rich-rule 'rule family="ipv4" service name="cockpit" source address="10.10.10.0/24" accept'

# Assign zone to network device
sudo firewall-cmd --permanent --zone=publicweb --change-interface=enp0s3

# Make new zone the default
sudo firewall-cmd --permanent --set-default-zone=publicweb

#########################################################################################

# Make permanent configuration active
firewall-cmd --reload












